# Generated by Django 3.2.16 on 2023-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=13.5, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
